#!/bin/bash

rm -f bench
iverilog -o bench bench.v llstub.v llmanager.v \
../../rtl/verilog/forks/sd_rrmux.v \
../../rtl/verilog/forks/sd_mirror.v \
../../rtl/verilog/closure/sd_output.v \
../../rtl/verilog/memory/behave2p_mem.v
./bench

