#!/bin/bash

rm -f bench
iverilog -o bench -Y .v bench.v fibstub.v llrdport.v llwrport.v \
llmanager.v llmanager_refcount.v \
../../rtl/verilog/forks/sd_rrmux.v \
../../rtl/verilog/forks/sd_mirror.v \
-y ../../rtl/verilog/closure \
-y ../../rtl/verilog/buffers \
../../rtl/verilog/memory/behave2p_mem.v
./bench | tee bench.log


