name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Icarus Verilog
      run: sudo apt install iverilog
    - name: Build and run fifo_s simulation
      run: python3 scripts/run_test.py --test fifo_s
    - name: Build and run fifo_c simulation
      run: python3 scripts/run_test.py --test fifo_c
    - name: Build and run rrmux simulation
      run: python3 scripts/run_test.py --test rrmux
    - name: Build and run fifo_b simulation
      run: python3 scripts/run_test.py --test fifo_b
    - name: Build and run test for timing closure components
      run: python3 scripts/run_test.py --test closure
